[package]
name = "mine-rs"
version = "0.0.1"
edition = "2021"
default-run = "mine-rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
