[package]
name = "mclib"
version = "0.1.0"
edition.workspace = true
publish = false

[features]
default = []
tokio-io = ["dep:tokio"]

[dependencies]
uuid = { version = "1", default-features = false }

tokio = { version = "1", optional = true, features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "io-util"] }

[lints]
workspace = true

